### PR TITLE
Updating pkt test to base standard

### PR DESCRIPTION
**Pull request by sweeksBigBlue**
Creating updated pull request for pkt_test.c. This included removing cne_printf() calls, wrapping vt_color() calls, and removing unnecessary '/n' characters to tst_XXX() calls [these naturally insert a '/n' for you].

### CODE REVIEW

**Review by eleemhui — APPROVED** [review]
looks good

**Review by leonmatt — APPROVED** [review]
LGTM

**Review by byron-marohn — APPROVED** [review]

**Comment by byron-marohn** [comment]
Ready to port over

**Comment by byron-marohn** [comment]
pulled into test_improvements branch to submit upstream

**Pull request closed without merging**
