### PR TITLE
Updating vector test standard

### PR DESCRIPTION
**Pull request by sweeksBigBlue**
This updates the vector test removing by removing all cne_printf() calls with tst_info() calls and adds a helper print function to print results.

### CODE REVIEW

**Comment by sweeksBigBlue** [comment]
image
old test format

image
new test format

**Comment by sweeksBigBlue** [comment]
@byron-marohn I don't see the github workflows going through with the clang linter, is there a way to check that? (Would be nice to have linting and everything on the up and up before trying to merge upstream).

**Comment by byron-marohn** [comment]
@sweeksBigBlue can you try making it a non-draft PR? I'm not sure why the github actions aren't running

**Comment by sweeksBigBlue** [comment]
@byron-marohn still not running
image

I did dig through the main target branches PRs and there should be a few runs. We also should be seeing docker checks when we change that. So I am wondering if there is a configuration issue.

**Review by eleemhui — APPROVED** [review]
Looks good

**Review by byron-marohn — APPROVED** [review]

**Comment by byron-marohn** [comment]
Was merged upstream

**Pull request closed without merging**
